/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Putra
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    private static MainMenu instance;

    
    public static MainMenu getInstance() {
    if (instance == null) {
        instance = new MainMenu();
    }
    return instance;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pelangganButton = new javax.swing.JButton();
        pcButton = new javax.swing.JButton();
        penyewaanButton = new javax.swing.JButton();
        laporanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Aplikasi Penyewaan PC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(57, 62, 70));

        pelangganButton.setBackground(new java.awt.Color(0, 173, 181));
        pelangganButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        pelangganButton.setText("Pelanggan");
        pelangganButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganButtonActionPerformed(evt);
            }
        });

        pcButton.setBackground(new java.awt.Color(0, 173, 181));
        pcButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pcButton.setForeground(new java.awt.Color(255, 255, 255));
        pcButton.setText("PC");
        pcButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcButtonActionPerformed(evt);
            }
        });

        penyewaanButton.setBackground(new java.awt.Color(0, 173, 181));
        penyewaanButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        penyewaanButton.setForeground(new java.awt.Color(255, 255, 255));
        penyewaanButton.setText("Penyewaan");
        penyewaanButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        penyewaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyewaanButtonActionPerformed(evt);
            }
        });

        laporanButton.setBackground(new java.awt.Color(0, 173, 181));
        laporanButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        laporanButton.setForeground(new java.awt.Color(255, 255, 255));
        laporanButton.setText("Laporan");
        laporanButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laporanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(penyewaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penyewaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganButtonActionPerformed
         this.setVisible(false); // Sembunyikan MainMenu
    PelangganForm pelangganForm = new PelangganForm(); // Buat instance PelangganForm
    pelangganForm.setVisible(true); // Tampilkan PelangganForm
    pelangganForm.setLocationRelativeTo(null); // Atur agar form muncul di tengah layar
    }//GEN-LAST:event_pelangganButtonActionPerformed

    private void pcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcButtonActionPerformed
        this.setVisible(false); // Sembunyikan MainMenu
    PcForm pcForm = new PcForm(); // Buat instance form PC
    pcForm.setVisible(true); // Tampilkan PCForm
    pcForm.setLocationRelativeTo(null); // Atur agar form muncul di tengah layar
    }//GEN-LAST:event_pcButtonActionPerformed

    private void penyewaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyewaanButtonActionPerformed
        this.setVisible(false); // Sembunyikan MainMenu
    PenyewaanForm penyewaanForm = new PenyewaanForm(); // Buat instance PenyewaanForm
    penyewaanForm.setVisible(true); // Tampilkan PenyewaanForm
    penyewaanForm.setLocationRelativeTo(null); // Atur agar form muncul di tengah layar
    }//GEN-LAST:event_penyewaanButtonActionPerformed

    private void laporanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanButtonActionPerformed
          this.setVisible(false); // Sembunyikan MainMenu
    LaporanForm laporanForm = new LaporanForm(); // Buat instance LaporanForm
    laporanForm.setVisible(true); // Tampilkan LaporanForm
    laporanForm.setLocationRelativeTo(null); // Atur agar form muncul di tengah layar
    }//GEN-LAST:event_laporanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            MainMenu.getInstance().setVisible(true); // Panggil instance MainMenu
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton laporanButton;
    private javax.swing.JButton pcButton;
    private javax.swing.JButton pelangganButton;
    private javax.swing.JButton penyewaanButton;
    // End of variables declaration//GEN-END:variables
}
